name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: ghcr.io/dvcorg/cml-py3
    steps:
     
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc 
          pip install -r requirements.txt
          dagshub > report.md
          cml comment create --publish --pr=false report.md



