name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: dvcorg/cml-py3
    steps:
     
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          pip install -r ./requirements.txt
          dagshub > report.md
          dvc doctor
          
          cml comment create --publish --pr=false report.md



