name: CML & DVC
on: [push]
jobs:
  train-and-report:
    runs-on: DESKTOP-V5ILVNP
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc 
          pip install -r requirements.txt
          dagshub > report.md
          cml comment create --publish --pr=false report.md



